---
title: "Shiny App"
author: "Michael Schulte & Austin Webb"
date: "2022-07-28"
output: html_document
runtime: shiny
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
# Install the packages
library(shiny)
library(ggplot2)
library(tidyverse)
```


```{r echo = FALSE}


# Start User Interface
ui <- shinyUI(fluidPage(# Title
  titlePanel("Housing"),
  tabsetPanel(
    # First Tab Title
    tabPanel(
      "Upload File",
      titlePanel("Uploading Files"),
      sidebarLayout(
        sidebarPanel(
          # Upload file button
          fileInput(
            'file1',
            'Choose CSV File',
            accept = c('text/csv',
                       'text/comma-separated-values,text/plain',
                       '.csv')
          ),
          tags$br(),
          # Does the file have headers button
          checkboxInput('header', 'Header', TRUE),
          # What is the delimiter button
          radioButtons('sep', 'Separator',
                       c(
                         Comma = ',',
                         Semicolon = ';',
                         Tab = '\t'
                       ),
                       ','),
          # Quotes button
          radioButtons(
            'quote',
            'Quote',
            c(
              None = '',
              'Double Quote' = '"',
              'Single Quote' = "'"
            ),
            '"'
          ),
        ),
        # End of sidebar panel
        
        mainPanel(
          # Output table
          tableOutput('contents'),
          tags$h4('Not all observations and features are shown.')
        ) # End of main panel
      )
    ),
    # Second Tab Title
    tabPanel(
      "Plots",
      pageWithSidebar(
        headerPanel('Plots'),
        sidebarPanel(
          # Empty inputs - they will be updated after the data is uploaded
          selectInput('xcol', 'X Variable', ""),
          selectInput('ycol', 'Y Variable', "", selected = ""),
          
          # Filter neighborhoods
          selectInput('Neighborhood', label = ('Choose Neighborhood'), ''),
          
          # Pick a plot
          selectInput(
            'Plot',
            label = ('Which Plot?'),
            choices = list(
              'Scatter' = 'Scatter',
              'Box' = 'Box',
              'Histogram' = 'Histogram'
            )
          ),
          
          # regression line
          checkboxInput("Regression", "Add regression line?")
        ),
        # End of sidebar panel
        
        mainPanel(
          # Title of first plot
          titlePanel('All Neighborhoods'),
          # Output first plot
          plotOutput('MyPlot'),
          
          # Title of second (Filtered) plot
          titlePanel('Filtered Neighborhoods'),
          # Output second plot
          plotOutput('filteredPlot'),
          tags$br()
        )
      )
    )
    
  )))

server <- shinyServer(function(input, output, session) {
  data <- reactive({
    # Require input
    req(input$file1)
    # Assign input to inFile
    inFile <- input$file1
    # Assign the csv to a dataframe called df
    df <-
      read.csv(
        inFile$datapath,
        header = input$header,
        sep = input$sep,
        quote = input$quote
      )
    
    
    # Update x inputs
    updateSelectInput(
      session,
      inputId = 'xcol',
      label = 'X Variable',
      choices = names(df),
      selected = names(df)
    )
    # Update y inputs
    updateSelectInput(
      session,
      inputId = 'ycol',
      label = 'Y Variable',
      choices = names(df),
      selected = names(df)[2]
    )
    # Update filter inputs
    updateSelectInput(
      session,
      inputId = 'Neighborhood',
      label = 'Neighborhood',
      choices = df$Neighborhood,
      selected = df$Neighborhood
    )
    
    return(df)
  })
  
  # Output table
  output$contents <- renderTable({
    # Output the head of the data and only first eight columns
    head(data() %>% select(1:8))
  })
  
  # Output first plot
  output$MyPlot <- renderPlot({
    # Histogram
    if (input$Plot == 'Histogram') {
      ggplot(data(), aes_string(x = input$xcol)) +
        geom_histogram(color = 'blue', fill = 'red')
    } # End of if histogram
    
    # Scatterplot
    else if (input$Plot == 'Scatter') {
      # Regression line
      if (input$Regression) {
        ggplot(data(), aes_string(x = input$xcol, y = input$ycol)) +
          geom_point(color = 'red') +
          geom_smooth(method = lm,
                      color = 'blue',
                      fill = 'blue')
      } # end regression if statement
      else {
        ggplot(data(), aes_string(x = input$xcol, y = input$ycol)) +
          geom_point(color = 'red')
      } # end else regression statement
    } # End of scatterplot
    
    # Boxplot
    else {
      ggplot(data(), aes_string(x = input$xcol, y = input$ycol)) +
        geom_boxplot(fill = 'red',
                     color = 'blue')
    }
  })
  
  
  # output filtered plot
  output$filteredPlot <- renderPlot({
    # If statement to filter by Neighborhood
    if (input$Neighborhood == 'All') {
      filtered <- data()
    } else {
      filtered <- data() %>% filter(Neighborhood == input$Neighborhood)
    }
    
    # Histogram
    if (input$Plot == 'Histogram') {
      ggplot(filtered, aes_string(x = input$xcol)) +
        geom_histogram(color = 'blue', fill = 'red')
    } # End of if histogram
    
    # Scatterplot
    else if (input$Plot == 'Scatter') {
      # Regression
      if (input$Regression) {
        ggplot(filtered, aes_string(x = input$xcol, y = input$ycol)) +
          geom_point(color = 'red') +
          geom_smooth(method = lm,
                      color = 'blue',
                      fill = 'blue')
      } # end regression if statement
      else {
        ggplot(filtered, aes_string(x = input$xcol, y = input$ycol)) +
          geom_point(color = 'red')
      } # end else regression statement
    } # End of scatterplot
    
    # Boxplot
    else {
      ggplot(filtered, aes_string(x = input$xcol, y = input$ycol)) +
        geom_boxplot(fill = 'red',
                     color = 'blue')
    }
  })
  
})

shinyApp(ui, server)

```

