---
output: html_document
---

## Introduction

<br>

### Who am I?
Hello! My name is Austin Webb. I've spent time in Arizona, Utah, and Hawaii but will always call Texas home, it is pretty much the greatest place on Earth. I am very passionate about sports, and only cheer for the best teams: The Cowboys and The Mavericks. I also really enjoy traveling and seeing the world, and maybe one day I will be able to fill up a passport book, because that would be pretty awesome. 

### Schooling
I went to BYU for my undergrad where I majored in statistics and analytics. I am currently pursing a masters degree in data science from SMU. My expected graduation date is December 2023. I am excited to take what I have learned from my schooling and apply it to the next chapter in my life. 

### Hobbies
When I am not glued to my computer coding, I look to look at basketball statistics. It combines my two loves, sports and statistics. Not to brag, but I am the current "Webb" champion in ping-pong, it is very impressive, I know. I really like being active. I love to play pickleball, go bouldering, swim, and do pretty much anything that gets me outside. 